Open Data Kit Template files for Project Location Data
openkfw/open-geodata-model pull request #18
Opened 2024-03-05 09:24 UTC by ckreutz

2024-03-05 09:51 UTC, fretchen commented
Looks pretty cool to me.
As for the forms there are other people to judge on their content (@Maja4Dev  or @Jo-Schie ) ?

However, I wonder if we could have some (minimal ?) documentation on these two files ?  As a user I would wonder:

- Why does the repo have two xlsx files ? Which one should I use when ?
- Is the xlm file connected to the rest in any fashion ?

One possible solution would be to have a short explanation in some small `md` file on the topic of odk etc ?

2024-03-06 11:01 UTC, ckreutz commented
@fretchen yes sure but I would add this to the Readme file. Shall I push a draft version / addition?

2024-03-07 12:31 UTC, Maja4Dev requested changes
Regarding the drop-down list of the KC-Themes, please put _Generic / Cross-sectoral first. 

Please update the KC-Theme names to the latest template v02 in this repo - in the Table "Fill-me" in column N drop down list.

Please update all location type names to the same latest version by using the table "Location Types IATI and New".

Please add to the DAC 5 Purpose Classification the following sentence: "The DAC 5 Purpose Codes (one to four) for the entire project have to be provided by your KfW counterpart. In case there are more than one codes for the project, you have to assign the correct code to each location. In case all codes have to be assigned to all locations, then please create a new row for each location, with the only difference being the DAC 5 Purpose Classification. 

Please add the field "Alternative Location Type Name" and its comment from the above template.

Geographic Exactness: we have four options now - please update from fill-me, column S.

Related Community / Village / Neighborhood: Plese update the comment text in the above template, table fill-in, Column V.

2024-03-14 11:35 UTC, ckreutz commented
@Maja4Dev added the changes to the template files. 
@fretchen added an explanation in the readme file.

2024-03-14 16:52 UTC, maevedefrance commented
Hi there, sorry in advance for the length of the post and if any of these points are off topic, but this can happen with an external point of view 😊. I admit I didn't read all the associated documentation, but also on purpose, as I think it's useful to have such data collection tools as self-explanatory as possible to make sure everything is done for a quality data collection.

I guess the users will be perfectly aware/trained on all the notions etc explained (as else very hard to get the whole understanding for someone who does not have prior knowledge)? Because I doubt that many will open the external documentation, so it can be good to embed it further as hints/explanations in the form in my opinion. Relatedly, I would add a clearer title to the form, a quick intro explaining the purpose for the user (who is capturing, when & why), perhaps some section labels to give it flow/ for better readability (project general information, location specific info, location specific geo etc)? Perhaps add color/bold to some labels to make sure some elements are well read/ user friendly, ie start and end date in the activity_start /activity_end labels (https://xlsform.org/en/#styling-prompts).


Here is more specific feedback:
**Unique-ID :** 
-	It’s not clear to me for new locations what should be done for the code, as the variable is mandatory. Is there any guidance on how it should be built that could be added to the hint? Or a skip pattern on whether it’s new or not to be added to deal with the case?
-	For the hint, maybe talk of variable rather than column, easier for the person collecting the data to understand

**All text / number / data variables:** any constraints that should be added (Regex- https://cartong.pages.gitlab.cartong.org/learning-corner/en/5_survey_design_mdc/5_6_form/5_6_4_validation_criteria#use-of-regex--when-how-and-examples-in-the-humanitarian-and-development-fields)  or min/max for ex) to avoid errors? For example for it to be in a range of numbers, to start with a letter and then have X numbers, for there to be a min and max date or budget, to avoid avoidatable errors. Even just making sure there is no negative data captured:)

**Data owner:** perhaps add example in hint to make it more user friendly? I suppose a dropdown list with an “if other, please specify” would be too complicated to compile?

**publishing_restrictions**: will the person answering always know for sure if yes or no, or should a “to be discussed further” option be useful?

**Location name:** what should they do if there is no name? Describe its location, write NA?
Location Activity Status: there is no need to have an “if other please specify”? Just checking

**Additional Activity-Description :** would it make sense to make the text multiline in appearance so they can describe in more detail? I guess this depends if data is collected on web at all, which I imagine it is?

**KC Theme/Sub-sector:** I guess this is not finalised, but the names are not coded in a format that is exploitable, they are “just” normal labels, so the cascading lists can’t work -there are spaces, special characters etc)

**DAC 5:** don’t get the new row for each location, you mean a new submission? Or do you want a repeat group in the form so that a series of location per project can be captured inside one submission?

**Budget share:** same, do you want this in a repeat group, to then be able to make and check the sums through calculations? Sorry if off topic, hard for me to be sure of the general logic of what is being collected

**Latitude & Longitude:** If the data is not always captured in the field, could you not at least have a skip pattern to make a GPS type variable usable if relevant (as so much easier / less error prone…). Or if using an online app like Enketo in Kobo for capture, to be able to capture it by pointing on the map as such tools make possible? And if “yet unknown”, should there not be a skip pattern so the latitude/longitude not be captured, or else not make it mandatory? 

**Do you want any [metadata]**(https://cartong.pages.gitlab.cartong.org/learning-corner/en/5_survey_design_mdc/5_6_form/5_6_6_quality_control) (such as when the submission was started/ended?) or is it not useful?


And just a side note that made me smile- I just saw in the “start here” tab a mention of our XLSForm cheat sheet, that I initiated a few years ago, nice to see it being used 😊.

hope this is useful, don't hesitate if you have further questions,
Maeve

2024-03-22 08:31 UTC, fretchen commented
Given the (possible ?) complexity of the suggested changes I opened a new issue #25 and this gives us also time to work through them step-by-step ? However, I would be curious if we see some blockers @maevedefrance ?

For tracking the status let us take a list here:

- [ ] Unique-ID
- [ ] All text / number / data variables
- [ ] Data owner
- [ ] publishing_restrictions
- [ ] Location name
- [ ] Location Activity Status
- [ ] Additional Activity-Description
- [ ] KC Theme/Sub-sector
- [ ] DAC 5
- [ ] Budget share
- [ ] Latitude & Longitude
- [ ] Metadata

2024-03-22 11:07 UTC, ckreutz commented
Dear all, 

I do not understand, why this shall be all done within the pull request. The current version works and is validated. I would build on it instead of holding this version back. This is the whole logic of a Github repo. 😀  The feedback from @maevedefrance is really helpful, but these are improvements and not pointers to breaking issues or am I missing here something? The basic logic is there and grouping etc. is the cherry on the cake.

2024-03-22 18:10 UTC, merged