Maja4 dev patch 1 Sample Geodata ToR
openkfw/open-geodata-model pull request #21
Opened 2024-03-12 11:26 UTC by Maja4Dev

These are the new Sample ToR for KfW Project location data collection and management which KfW counterparts need to amend and complete and then to forward to their project's Project Executing Agency (PEA) and / or their Implementation Consultant for data collection and updating.

2024-03-12 13:48 UTC, fretchen requested changes
I recommend a number of changes. 

- [ ] The changes on the index.md should not be in this branch as they are already present in  #20 . So we can wait until #20 is merged and then look for the diff or simply remove them from this branch.
- [ ] Geodat_ToR is not a markdown file yet. This should be changed. 
- [ ] This file should be added to the mkdocs.yml file line 15 or 16 such that it is also in the final compiled file...

As for the content I cannot judge....

2024-03-18 07:46 UTC, goergen95 commented
Hi @Maja4Dev,

thanks for opening the PR. There are three main points I am still uncomfortable with these ToR.

- The provision of the ToR are a burden to technical adapt partners. For partners with elaborated GIS systems there are better formats/procedures for the exchange of geospatial information. I would be against KfW making it mandatory for them to deliver their data in sub-optimal and proprietary data formats.
  
- Currently there is the lack of a clear process how the governance of future changes to the specification looks like. This is very much required if KfW wants to make it legally binding for partners to adhere to the specifiation. Then, partners need to know which version is the legally binding one, how changes are being handled on what that means for them during the lifetime of a project.
  
- KfW needs tooling to check if incoming data adheres to the standard. As long as KfW does not have such tooling it is really hard for anyone to assess the integrity of the data. Ideally, such tooling should be developed openly (e.g. in this repo) so that technical adapt partners can use the tools too to check their data before sending it to KfW.
  
Happy to further discuss this during a dedicated meeting.

2024-03-21 19:25 UTC, Maja4Dev commented
Hi @goergen95 : The ToR are necessary for our KfW colleagues to be able to request the data collection from their implementing partners - regardless which data collection template will be used. 

Without ToR, no data will be collected for KfW. 

The filling out of the sample ToR (yellow-highlighted text) allows KfW staff to enter project-specific information which the data collector may need to have - such as the DAC-codes of the project, a.o.

Once we have better formats for data collection, we can easily add or replace them in the sample ToR. But there will be for many years still be some data collectors that will need the excel template.

Regarding the clear process how the governance of future changes to the specification looks like: from my perspective the (latest ) template published here in Github is the currently valid one. If we have more that one format (e.g. Excel and Kobo Toolbox and / or languages - they should all present an identical data model). Which other specifications do you need? Do you want to make a proposition?   
There should be definitely tooling to check if incoming data adheres to the standard. It would be great if this could be published here in Github, please discuss with @Jo-Schie .

2024-03-21 19:27 UTC, Maja4Dev commented
Hi @fretchen,
happy to implement your recommendations, but need your help 😅.

2024-03-22 08:21 UTC, fretchen commented
So I have a few propositions.

- The discussion on the process is moved into #23 
- The discussion on a streamlined data format can be found in #24
- I am not sure if the clear tooling needs an extra issue or if this is part of the other open PRs and issues @goergen95 ?

@Maja4Dev 
- I created a PR to implement most of the suggested changes [here](https://github.com/Maja4Dev/open-geodata-model/pull/2).
- However, I also think that we still need to sit together to fix some layout problems...

2024-03-25 13:45 UTC, fretchen approved these changes
LGTM now especially as the content of the already existing RMMV Guidebook did not change.

2024-03-25 15:09 UTC, fretchen commented on docs/sample_tor.md
> +-	The Following Data Fields stated as Non-Mandatory in the Excel/Kobo-Template are to be filled out for this project {== (boxes below to be checked by KfW) ==}:
```suggestion
-	The Following Data Fields stated as Non-Mandatory in the Excel Template are to be filled out for this project {== (boxes below to be checked by KfW) ==}: 
```

2024-03-25 15:09 UTC, fretchen commented on docs/sample_tor.md
> +-	If a {== Geographic Information System (GIS), (Remote) Management Information System (R/MIS) or Maintenance Management System (MMS) (*please choose which*) ==} is used in the project, then the exis
```suggestion
-	If a {== Geographic Information System (GIS), (Remote) Management Information System (R/MIS) or Maintenance Management System (MMS) (*please choose which*) ==} is used in the project, then the existing location IDs can be entered also in the Excel template as Project-Specific Location Identifiers (Column G in the Table “Fill-Me” in the project location data [Excel template](https://github.com/openkfw/open-geodata-model/blob/main/Project_Location_Data_Template_V02.xlsx). This makes it easier to check location data across project partner systems and verify the use of funds.
```

2024-03-25 15:10 UTC, fretchen commented on docs/sample_tor.md
> +The [KfW’s Project Location Geodata Model](https://github.com/openkfw/open-geodata-model) is part of these ToR including the Excel / Kobo Template as well as the Location Type Icons currently being u
```suggestion
The [KfW’s Project Location Geodata Model](https://github.com/openkfw/open-geodata-model) is part of these ToR including the Excel Template as well as the Location Type Icons currently being updated and both to be found under the same link above. 
```

2024-03-25 15:43 UTC, merged