Create kobo_guide_V1.md
openkfw/open-geodata-model pull request #36
Opened 2024-03-26 14:06 UTC by S-r-f-l

Kobo Guide version 1

2024-03-27 07:42 UTC, fretchen requested changes
I think that this is a nice starting point. I already added a number of comments where fitting. 

- [ ] could you update the mkdocs.yml to add this to the documentation ?
- [ ] Could you  add a "note" at the beginning which mentions that this is still an early phase and we are testing out the workflow ?
- [ ] rename the file to kobo_guide.md ?

2024-03-27 07:42 UTC, fretchen commented on docs/kobo_guide_V1.md
> +Welcome to our comprehensive guide on using KoboToolbox for gathering geographical data. In today's digital age, efficient data collection is crucial for various projects, from research initiatives t
Sounds pretty much like taken from their website ? Could you add a link ? I like the [Cheat Sheet](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet)

2024-03-27 07:42 UTC, fretchen commented on docs/kobo_guide_V1.md
> +This Introduction aims to harness the capabilities of KoboToolbox to gather geo data for variaty of projects. By following the steps outlined in this guide, you will be equipped to use the provided .
Double parenthesis is too much at the end.
Which xls file is meant ?
Could you also state that the file is an [XLSForm ](https://xlsform.org/en/)

2024-03-27 07:42 UTC, fretchen commented on docs/kobo_guide_V1.md
> +**Reminder:* Please Download the followind Excel file before continuing with the steps to use the KoboToolbox:
Best to work with the link syntax instead of bare link IMHO...

2024-03-27 07:42 UTC, fretchen commented on docs/kobo_guide_V1.md
> +7. **Regular Maintenance:**
I think that we can skip this part for the moment...

2024-03-27 07:42 UTC, fretchen commented on docs/kobo_guide_V1.md
> +8. **Backup and Security:**
We can also skip this for the moment I would say...

2024-03-27 07:42 UTC, fretchen commented on docs/kobo_guide_V1.md
> +Remember, this guide provides a basic overview of using KoboToolbox. For more advanced features and functionalities, refer to the official documentation and resources provided by KoboToolbox.
We can also remove this.

2024-04-08 14:52 UTC, fretchen requested changes
Almost there...

2024-04-08 14:52 UTC, fretchen commented on docs/kobo_guide.md
> +**Disclaimer:* This guide is in the early phase of development, and we are currently testing out the workflow. Please bear with us as we refine the content and improve the workflow. Your feedback and
I would remove the disclaimer here.

2024-04-09 08:30 UTC, S-r-f-l commented on docs/kobo_guide.md
> +**Disclaimer:* This guide is in the early phase of development, and we are currently testing out the workflow. Please bear with us as we refine the content and improve the workflow. Your feedback and
done

2024-04-09 08:53 UTC, merged