Create overview_templates_tor page
openkfw/open-geodata-model pull request #51
Opened 2024-05-17 12:01 UTC by Maja4Dev

Only the new Page "Overview Sample ToR and Templates" should be merged

2024-05-17 12:26 UTC, fretchen requested changes
This sounds interesting. However, a few commands.

- The file should be moved into the docs folder, as the other files are there too.
- The file should have the ending `.md` to be clearly marked as a markdown file.
- The file is currently not mentionned in the `mkdocs.yml` file. So it will not be visible in the published page.
- It is unclear what is meant with "only this file should be merged". Currently there is only one file with changes visible.

Further commands will come below.

2024-05-17 12:28 UTC, fretchen commented on overview_templates_tor
> +## Protected Areas Project Location Data Collection: coming soon!
This is very unusual too put on a technical website. I would refrain from such announcements if there is not even an issue in this regard. So I would remove it.

2024-05-17 12:33 UTC, fretchen reviewed
Some more comments on the content.

2024-05-17 12:33 UTC, fretchen commented on overview_templates_tor
> +- [Terms de Reference](https://openkfw.github.io/open-geodata-model/sample_tor_fr/)
This file does not exist yet. So it cannot be linked yet.

2024-05-17 12:33 UTC, fretchen commented on overview_templates_tor
> +**English versions** (updated EN version from 22.05.2024):
This date is in the future. I would refrain from such statements on a website. It will be there, when it will be there.

2024-05-17 12:33 UTC, fretchen commented on overview_templates_tor
> +In case you want to verify you Excel template data before submitting it to KfW, we recommend this [Tutorial](https://openkfw.github.io/open-geodata-model/tutorials/xls_to_kml/)
This is a python tutorial. So I am absolutely not sure if it is ideal to send people there as a first introduction.

2024-05-17 12:33 UTC, fretchen commented on overview_templates_tor
> +Usually, the project's Proejct Excecuting Agency (PEA) and/or Consultant are to collect the location data of their respective project(s) with KfW. For each project, PEA and KfW agree on the amended s
Who decided this ? Is this already official KfW policy that is written somewhere in some public / internal documents ?

2024-05-17 12:33 UTC, fretchen commented on overview_templates_tor
> +Please have a look at the [Technical Notes](https://openkfw.github.io/open-geodata-model/technical_notes/) on how to fill out the Excel Template. You will find the same technical notes also in the ta
It is acutally possible to link directly [Technical Notes](technical_notes). This makes the code more robust if the website should be moved...

2024-05-17 14:31 UTC, Maja4Dev commented on overview_templates_tor
> +Usually, the project's Proejct Excecuting Agency (PEA) and/or Consultant are to collect the location data of their respective project(s) with KfW. For each project, PEA and KfW agree on the amended s
Yes, it is in the OHB.

2024-05-17 14:36 UTC, Maja4Dev reviewed
Here my feedback on @fretchen's comments.

2024-05-17 14:36 UTC, Maja4Dev commented on overview_templates_tor
> +- [Terms de Reference](https://openkfw.github.io/open-geodata-model/sample_tor_fr/)
And if I start an issue to add it now?

2024-05-17 14:36 UTC, Maja4Dev commented on overview_templates_tor
> +## Protected Areas Project Location Data Collection: coming soon!
Ok. Just wanted to show Johannes where I would put his Protected Areas docs.

2024-05-17 14:36 UTC, Maja4Dev commented on overview_templates_tor
> +Please have a look at the [Technical Notes](https://openkfw.github.io/open-geodata-model/technical_notes/) on how to fill out the Excel Template. You will find the same technical notes also in the ta
ok.

2024-05-17 14:36 UTC, Maja4Dev commented on overview_templates_tor
> +In case you want to verify you Excel template data before submitting it to KfW, we recommend this [Tutorial](https://openkfw.github.io/open-geodata-model/tutorials/xls_to_kml/)
ok, then better delete this phrase.

2024-05-17 14:40 UTC, fretchen commented on overview_templates_tor
> +- [Terms de Reference](https://openkfw.github.io/open-geodata-model/sample_tor_fr/)
Then you should add the comment in the according PR. This way this PR can be merged and is not blocked by the french ToR.

2024-05-17 16:03 UTC, fretchen commented
This locks already helpful. The remaining problems are:

- [ ] the page is still not added under the [mkdocs.yml](https://github.com/openkfw/open-geodata-model/blob/47-new-page-concerning-the-template-and-tors/mkdocs.yml) in the nav section. So it wil not be shown.
- [ ] It is still not clear what you meant with "only this file should be merged".
- [ ] The way you set it up, this PR is now blocked by #55 and will have to wait until it is merged. Otherwise, you could simply add this section on the french section once #55 is ready and reviewed (what I would recommend)...

2024-05-22 11:18 UTC, Jo-Schie commented
checked with maja and seems okay

2024-05-22 11:18 UTC, merged